version: "3"  
services:  
  
  # ----------------- #  
  #    File-server    # 
  # ----------------- #
  file-server:  
    container_name: smart-parking-server  
    build:   
       context: .
       dockerfile: Dockerfile.dev
    ports:  
      - "3000:3000"  

