# Fetching the minified node image on apline linux
FROM node:slim

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}


# Setting up the work directory
WORKDIR /app

COPY package.json ./
RUN yarn config set network-timeout 600000 -g && yarn install

COPY . .

EXPOSE 3000

CMD [ "yarn", "start" ]
